# Generated by Django 4.2.4 on 2023-09-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='Sur_name',
            field=models.TextField(default='t'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='First_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='messages',
            name='Last_name',
            field=models.TextField(),
        ),
    ]
