# Generated by Django 4.2.4 on 2023-09-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_messages_email_remove_messages_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='name',
            new_name='message',
        ),
        migrations.AddField(
            model_name='messages',
            name='email',
            field=models.EmailField(default='e', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='person',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
