# Generated by Django 4.2.4 on 2023-09-03 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_name_messages_message_messages_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Software',
        ),
    ]
