# Generated by Django 4.2.4 on 2023-09-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='upload',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
