# Generated by Django 4.2.4 on 2023-09-30 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_reviews_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='id_of_soft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.software'),
        ),
    ]
